# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  
  - npm i
  - npm run client:install

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
  - npm run start
  artifacts:
    expire_in: 1 week
    paths:
    - 'build/'



pages:
  stage: deploy
  script:
  - mv public _public
  - mv build public
  only:
  - master

  dependencies:
  - build1
